version: '3.8'

services:
  # PHP Development
  app-dev:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    container_name: ttms-app-dev
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ttms-network
    depends_on:
      - mysql
      - redis

  # PHP Production
  app-prod:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    container_name: ttms-app-prod
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ttms-network
    depends_on:
      - mysql
      - redis

  # Nginx Service
  nginx:
    image: nginx:1.19-alpine
    container_name: ttms-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - ttms-network
    depends_on:
      - app-dev
      - app-prod
      - dev

  # Frontend Development
  dev:
    image: node:18-alpine
    container_name: ttms-dev
    working_dir: /app
    command: sh -c "cd client && npm install && npm run dev -- --host"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    networks:
      - ttms-network

  # Frontend Production Build
  prod:
    image: node:18-alpine
    container_name: ttms-prod
    working_dir: /app/client
    volumes:
      - .:/app
    command: sh -c "npm ci && npm run build-only && mkdir -p /app/public/frontend && cp -R dist/* /app/public/frontend/"
    networks:
      - ttms-network

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: ttms-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ttms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: ttms
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - ttms-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: ttms-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ttms-network

networks:
  ttms-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
